[versions]
minecraft = "1.21.1"
neoForge = "21.1.217"
parchment = "2024.11.17"

[libraries]
emi-neoForge = { group = "dev.emi", name = "emi-neoforge", version = "1.1.22+1.21.1" }
blueberryLib = { group = "concerrox.blueberry", name = "blueberry", version = "1.0.0" }
lowDragLib2 = { group = "com.lowdragmc.ldlib2", name = "ldlib2-neoforge-1.21.1", version = "2.1.6.a" }
yoga = { group = "org.appliedenergistics.yoga", name = "yoga", version = "1.0.0" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.10.2" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.20" }
modDevGradle = { id = "net.neoforged.moddev", version = "2.0.134" }